on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ResourceGroup: repo-mirror
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2 
    - uses: actions/setup-dotnet@a71d1eb2c86af85faa8c772c03fb365e377e45ea # pin@v1 
    - name: build
      run: dotnet build -c Release
    - name: test
      run: dotnet test -c Release --no-build **/*.Test*.csproj
    - name: publish
      run: dotnet publish -c Release --no-build GitMirrorAutomation.Func/GitMirrorAutomation.Func.csproj -o release/GitMirrorAutomation.Func
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1 
      with:
        name: deploy
        path: deploy
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1 
      with:
        name: functionapp
        path: release/GitMirrorAutomation.Func
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@18f0f591fbc635562c815484d73b6e8e3980482e # pin@v1 
      with:
        name: functionapp
        path: functionapp
    - uses: actions/download-artifact@18f0f591fbc635562c815484d73b6e8e3980482e # pin@v1 
      with:
        name: deploy
        path: deploy
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI ARM deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          cd deploy
          chmod +x deploy.sh
          ./deploy.sh $ResourceGroup
    - uses: azure/functions-action@90060f5decddf3bb5ebf2c533607c4d4827cf8fa # pin@v1 
      with:
        app-name: ${{ env.ResourceGroup }}
        package: functionapp
